git:
  depth: 1

language: java

jdk:
  - openjdk11

before_script:
  - cd build

script:
  - ant clean
  - ant build -lib ../core/library-test/junit-4.8.1.jar -lib ../core/library-test/mockito-all-1.10.19.jar
