git:
  depth: 1

language: java

jdk:
  - openjdk11

before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo apt-get -qq update
  - sudo apt-get install openjdk-11-jdk
  - sudo apt-get install ant
  - sudo apt-get install ant-optional

before_script:
  - cd build

script:
  - ant clean
  - ant build
